# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=1000, verbose_name='\u5173\u952e\u8bcd\uff08\u82f1\u6587\u9017\u53f7\u5206\u9694\uff0c\u522b\u8d85\u8fc7\u56db\u4e2a\u5173\u952e\u8bcd\uff09')),
                ('description', models.CharField(max_length=1000, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u63a8\u5e7f\u4fe1\u606f',
                'verbose_name_plural': '\u63a8\u5e7f\u4fe1\u606f',
            },
        ),
        migrations.AlterModelOptions(
            name='base_article',
            options={'verbose_name': '\u57fa\u7840\u77e5\u8bc6\u6587\u7ae0', 'verbose_name_plural': '\u57fa\u7840\u77e5\u8bc6\u6587\u7ae0'},
        ),
        migrations.AlterField(
            model_name='page_content',
            name='position',
            field=models.IntegerField(choices=[(0, '\u9996\u9875\u8f6e\u64ad\u56fe\u6587\u5b57'), (1, '\u5173\u4e8e\u6211\u4eec'), (2, '\u52a0\u5165\u6211\u4eec\u4e0a\u65b9\u6587\u5b57'), (3, '\u52a0\u5165\u6211\u4eec\u4e0b\u65b9\u6587\u5b57'), (4, '\u4e3b\u9875\u53f3\u4e0b\u89d2\u6587\u5b57'), (5, '\u5bfc\u822a\u53f3\u4e0a\u65b9\u6587\u5b57')], verbose_name='\u6240\u5728\u4f4d\u7f6e'),
        ),
    ]
